# Introduction à Python

**INF600F - Traitement d'images (UQÀM)**
Tutoriel d'introduction à Python utilisé pour le cours de traitement d'images enseigné à l'UQAM. 
Professeur: Joël Lefebvre (https://linum-lab.ca)

## Introduction

In [2]:
a = 1.0
def fonction(a):
    a += 1
    return a

### Environnements Python

Ceci est un test

In [3]:
a = 1
print(a)

1


### Interpréteur

### Distribution Anaconda

### Façon d'exécuter du code Python
- Interpréteur
- Console
- IDE
- Jupyter

## Base du langage Python

### Indentation

In [3]:
def fonction(a):
    print(a)
    return a+1
    
fonction(1)

1


2

### Commentaires

In [4]:
a = 1 # asdlfkjasdlfkj

"""
asdflaksdj
asdlkfjasdlf
asdlfkjasdlf
"""

'\nasdflaksdj\nasdlkfjasdlf\nasdlfkjasdlf\n'

### Variables

In [5]:
a = 1
print(type(a))
a = 10.0
print(type(a))
a = "salut"
print(type(a))

<class 'int'>
<class 'float'>
<class 'str'>


### Opérateurs

In [6]:
a = 1
b = 2

a += 1
print(a)

2


### Boucles

In [7]:
for i in range(5):
    print(i)
    
a = ["python", "scipy"]
for i in a:
    print(i)
    
i = 0
while i < 4:
    print(i)
    i += 1

0
1
2
3
4
python
scipy
0
1
2
3


### Structures de contrôle

In [8]:
a = 4
if a < 10:
    print("a est plus petit que 10")
elif a < 20:
    print("a est entre 10 et 20")
else:
    print("a est plus grand 20")

a est plus petit que 10


## Structures de données

### Listes

In [9]:
a = list(range(10))
b = [x*x for x in a]
print(a)
print(b)

c = []
for x in a:
    c.append(x**2)
print(c)


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


### Tuples

In [10]:
a = [1,2,3] # Liste
b = (1,2,3) # Tuple
a[0] = 3
print(a)
b[0] = 3

[3, 2, 3]


TypeError: 'tuple' object does not support item assignment

### Sets

In [11]:
a = [1,2,3,4,4] # liste
b = set([1,2,3,4,4]) # set (ensemble)
print(a)
print(b)

[1, 2, 3, 4, 4]
{1, 2, 3, 4}


### Dicts

In [12]:
a = {"lang": "Python", "version": 3, "cours": "inf600f"}
print(a)
print(type(a))
print(a["cours"])
a["session"] = "hiver 2021"
print(a)

{'lang': 'Python', 'version': 3, 'cours': 'inf600f'}
<class 'dict'>
inf600f
{'lang': 'Python', 'version': 3, 'cours': 'inf600f', 'session': 'hiver 2021'}


## Gestion des fichiers

In [13]:
f = open("fichier.txt", "r")
for i in f.readlines():
    print(i)
f.close()

# Écrire des données dans un fichier
f = open("fichier2.txt", "w")
f.write("Salut")
f.close()

Bonjour tout le monde !

Ceci est la deuxième ligne



## Fonctions originales

In [14]:
def maFonction(a, b, option1=2):
    c = a + b
    c *= option1
    return c

maFonction(1,2)

import math
def calculerPropCercle(r):
    aire = math.pi * r ** 2
    circ = 2 * math.pi * r
    return aire, circ

print(calculerPropCercle(3))

(28.274333882308138, 18.84955592153876)


# Calcul avec Python

## Modules Python

In [15]:
import numpy as np # Liste, matrice, algèbre linéaire
import scipy # Algorithme et méthode prog. scientifique
import matplotlib.pyplot as plt # Visualisation (afficher les images)
import skimage # Traitement d'images (scikit-image)

A = np.zeros((3,3), dtype=np.uint8)
print(A)
print(A.shape)
print(A.dtype)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
(3, 3)
uint8


## Créer un module

In [16]:
# Dans un fichier séparé
# Nom ficher : monModule.py

version = "1.0"

def printpi():
    print("La valeur de pi est 3.1416")
    
    
import monModule
monModule.printpi()

La valeur de pi est 3.1416


## Charger un module

In [17]:
import monModule as M
M.printpi()

from monModule import printpi as p
p()

from numpy import zeros, ones
zeros((3,3))
ones((3,3))

from math import *
cos(3)


La valeur de pi est 3.1416
La valeur de pi est 3.1416


-0.9899924966004454

## Numpy

In [18]:
A = np.zeros((3,3))
B = np.ones((3,3))

print(A)
print(B)

C = A + B * 2

D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(D)
D[:,0]
D[1::,:]

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[4, 5, 6],
       [7, 8, 9]])

## Scipy

In [ ]:
from scipy import ndimage
A = np.zeros((512,512), dtype=np.uint8)
ndimage.filters.gaussian_filter(A, 2)

import imageio # I/O image
imageio.imread("nom_image.jpg")
imageio.imwrite("nom_image2.png")

## Matplotlib

In [ ]:
import matplotlib.pyplot as plt

plt.plot([0,1,2,3], [0,1,4,9], label="Courbe")
plt.xlabel("X")
plt.ylabel("Y")
plt.legend()
plt.title("Quadratique")
plt.show()

## Scikit

In [ ]:
from skimage import filters
from skimage import data

img = data.astronaut()
print(img.shape)
print(img.dtype)
print(type(img))

plt.imshow(img)
plt.axis("off")
plt.show()

## OpenCV (version Python)

In [ ]:
import cv2

# Références

- (Chityala, 2020) Chapitre 1 : Introduction to Python
- (Chityala, 2020) Chapitre 2 : Computing using Python Modules
- (Swinnen, 2012) Apprendre à programmer avec Python 3 ([URL](https://inforef.be/swi/python.htm), gratuit !)
- (Lacey, 2019) Python by example : learning to program in 150 challenges. Cambridge University Press. [Biblio](https://uqam-bib.on.worldcat.org/oclc/1103218955).
- Tutoriel Numpy : https://numpy.org/doc/stable/user/quickstart.html
- Documentation Jupyter : https://jupyter.org/documentation
- [Tutoriel Scipy](https://docs.scipy.org/doc/scipy/reference/tutorial/)
- [Tutoriel Matplotlib](https://matplotlib.org/tutorials/introductory/pyplot.html)
- https://scikit-image.org/